package com.pastpaperskenya.papers.business.model.product

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "product")
data class Product(
    @PrimaryKey val id: Int,
    val name: String?,
    val slug: String?,
    val permalink: String?,
    val date_created: String?,
    val date_created_gmt: String?,
    val date_modified: String?,
    val date_modified_gmt: String?,
    val type: String?,
    val status: String?,
    val featured: Boolean?,
    val catalog_visibility: String?,
    val description: String?,
    val short_description: String?,
    val sku:String?,
    val price: String?,
    val regular_price: String?,
    val sale_price: String?,
    val date_on_sale_from: String?,
    val date_on_sale_from_gmt: String?,
    val date_on_sale_to: String?,
    val date_on_sale_to_gmt: String?,
    val price_html: String?,
    val on_sale: Boolean?,
    val purchasable: Boolean?,
    val total_sales: Int?,
    val downloadable: Boolean?,
    val downloads: ArrayList<DownloadsProperty>?,
    val download_limit: Int?,
    val download_expiry: Int?,
    val external_url: String?,
    val button_text:String?,
    val tax_status: String?,
    val tax_class: String?,
    val manage_stock:Boolean?,
    val stock_quantity: Int?,
    val stock_status: String?,
    val backorders:String?,
    val backorders_allowed: Boolean?,
    val backordered: Boolean?,
    val sold_individually: Boolean?,
    val weight: String?,
    val dimensions: DimensionsProperty?,
    val shipping_required: Boolean?,
    val shipping_taxable: Boolean?,
    val shipping_class: String?,
    val shipping_class_id: Int?,
    val reviews_allowed: Boolean?,
    val average_rating: String?,
    val rating_count: Int?,
    val related_ids: ArrayList<Int>?,
    val upsell_ids: ArrayList<Int>?,
    val cross_sell_ids: ArrayList<Int>?,
    val parent_id: Int?,
    val purchase_note: String?,
    val categories: ArrayList<ProductCategory>?,
    val tags: ArrayList<TagsProperty>?,
    val images: ArrayList<ImageProperty?>?,
    val attributes: ArrayList<AttributesProperty>?,
    val default_attributes: ArrayList<DefaultProperty>?,
    val variations: ArrayList<Int>?,
    val grouped_products: ArrayList<Int>?,
    val menu_order: Int?,
    val meta_data: ArrayList<MetaDataProperty>?

)
